# Generated by Django 3.2.4 on 2021-07-13 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=2)),
                ('descricao', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('logradouro', models.CharField(max_length=60)),
                ('numero', models.IntegerField()),
                ('UF', models.CharField(max_length=2)),
                ('bairro', models.CharField(max_length=60)),
                ('CEP', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=60)),
                ('fone', models.CharField(max_length=15)),
                ('tipo', models.CharField(max_length=60)),
                ('CPF', models.CharField(max_length=15)),
                ('RG', models.CharField(max_length=15)),
                ('data_nascimento', models.DateTimeField()),
                ('SEXO', models.CharField(max_length=1)),
                ('CNPJ', models.CharField(max_length=20)),
                ('insc_estadual', models.CharField(max_length=20)),
                ('nome_fantasia', models.CharField(max_length=60)),
                ('nome_contato', models.CharField(max_length=60)),
                ('situacao', models.CharField(max_length=1)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=60)),
                ('situacao', models.CharField(max_length=1)),
                ('unidade', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoImpl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('tipo_cadastro', models.CharField(max_length=1)),
                ('ctrl_lote', models.CharField(default='S', max_length=1)),
                ('estoq_disp', models.FloatField(blank=True)),
                ('estoq', models.FloatField(blank=True)),
                ('qtde_minimo', models.FloatField(blank=True)),
                ('perc_comissao', models.FloatField(blank=True)),
                ('prod_promocao', models.CharField(blank=True, max_length=1)),
                ('situacao', models.CharField(max_length=1)),
                ('padrao_cb', models.CharField(max_length=20)),
                ('cod_barras', models.CharField(max_length=40)),
                ('preco_custo_caixa', models.FloatField()),
                ('perc_lucro_prod_caixa', models.FloatField()),
                ('preco_venda_caixa', models.FloatField()),
                ('fator_conversao', models.IntegerField()),
                ('preco_custo_fracionado', models.FloatField(blank=True)),
                ('perc_lucro_prod_fracionado', models.FloatField(blank=True)),
                ('preco_venda_fracionado', models.FloatField(blank=True)),
                ('data_validade', models.DateTimeField()),
                ('cod_fornec', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro.fornecedor')),
                ('cod_unidade_compra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='unidadeCompra', to='cadastro.unidade')),
                ('cod_unidade_venda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='unidadeVenda', to='cadastro.unidade')),
            ],
        ),
    ]
